const CHAT = {
    LOG_IN_CHAT : 'LOG_IN_CHAT',
    SET_NEW_FRIENDS_STATE   : 'SET_NEW_FRIENDS_STATE',
    CHANGE_MY_STATUS        : 'CHANGE_MY_STATUS',
    LOG_OUT_FROM_CHAT       : 'LOG_OUT_FROM_CHAT'
}

export default CHAT;
