const CHAT = {
    CHAT_CONNECT                 : 'CHAT_CONNECT',
    CHAT_DISCONNECT              : 'CHAT_DISCONNECT',
    CHAT_SET_NEW_FRIENDS_STATE   : 'CHAT_SET_NEW_FRIENDS_STATE',
    CHAT_CHANGE_USER_STATUS      : 'CHAT_CHANGE_USER_STATUS',
    CHAT_LOG_OUT                 : 'CHAT_LOG_OUT',
}

export default CHAT;
