const CHAT = {
    SET_ACTUAL_FRIEND_LIST  : 'SET_ACTUAL_FRIEND_LIST',
    NEW_FRIENDS_STATE       : 'NEW_FRIENDS_STATE',
    ADD_MY_MESSAGE          : 'ADD_MY_MESSAGE',
    CHANGE_FRIEND_STATUS    : 'CHANGE_FRIEND_STATUS',
    CHANGE_MY_STATUS        : 'CHANGE_MY_STATUS',
    LOG_OUT_FROM_CHAT       : 'LOG_OUT_FROM_CHAT'

}

export default CHAT;
