const STATUSES = {
    ONLINE:  'ONLINE',

    CARD_CRETE_DECK: 'CARD_GAME_CRETE_DECK',
    CARD_FINDING_GAME: 'CARD_FIND_GAME',
    CARD_START_GAME: 'CARD_START_GAME',
    CARD_FINISH_GAME: 'CARD_FINISH_GAME',

    OFFLINE: 'OFFLINE'
}

module.exports  = STATUSES;